### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by miladr0** [arulajeh/adakerja-nodejs#1]
hi @arulajeh 
this is milad from Adakerja 🙌
Thank you for the time and effort you put in to make this task.

just one question: I didn't see any tests for main flow or some routes. is it possible for you to create some tests?
tnx

**Comment by arulajeh** [comment]
hi @miladr0 

I've added some tests to the api, and I've also added a few notes to Readme.md. You can check the latest version.

Regards,
Syahrulloh
